-- SubsTrack now uses MongoDB (Mongoose).
-- Collections are created automatically on first use:
--   users, subscriptions, sharedsubscriptions, budgetsettings, passwordresettokens
--
-- Start MongoDB locally, then set MONGODB_URI in .env:
--   MONGODB_URI=mongodb://127.0.0.1:27017/substrack_db
--
-- Optional: MongoDB Atlas connection string
--   MONGODB_URI=mongodb+srv://<user>:<password>@cluster.mongodb.net/substrack_db
